# Jekyll theme
remote_theme: open-and-sustainable/greendoc_theme
# title and description, URLs
title: "prismAId"
description: "Documentation of prismAId"
baseurl: ""
url: "https://prismaid.review"
github_repo: "https://github.com/open-and-sustainable/prismaid"
# logo and favicon
logo: "assets/images/prismaid-logo.png"
favicon: "assets/images/prismaid-favicon.ico"
# configuration of navigation entries
nav_links:
    - name: "Installation<br>& Setup"
      url: "/installation-setup.html"
    - name: "Screening<br>Tool"
      url: "/screening-tool.html"
    - name: "Download<br>Tool"
      url: "/download-tool.html"
    - name: "Convert<br>Tool"
      url: "/convert-tool.html"
    - name: "Review<br>Tool"
      url: "/review-tool.html"
    - name: "Review<br>Configurator"
      url: "/review-configurator.html"
    - name: "Review<br>Support"
      url: "/review-support.html"
    - name: "Help &<br>Development"
      url: "/help-development.html"
# configuration of custom colors
nav_background_color: "#0056b3" # Override nav bar color (darker blue)
nav_hover_color: "#007BFF" # Override hover color (blue)
nav_link_color: "#ffffff" # Override link text color (white)
toc-hover-color: "#007BFF" # Override TOC hover color (blue)
